import {
  smartWatch,
  glases,
  prfanChildren,
  childrenClothes,
  dress,
  paintsWommen,
  cut,
  paintsMens,
  cap,
  paintsWommen2,
  parfanMens,
  parfanWommen,
  shosewommen,
  shoseMen,
  chemese,
  T_ShirtWommen,
} from "../assets/category";

export const imageList = [
  { id: 1, name: "Smart Watches", href: "/smart-watches", img: smartWatch },
  { id: 2, name: "Glasses", href: "/glasses", img: glases },
  { id: 3, name: "Children's Perfume", href: "/children-perfume", img: prfanChildren, },
  { id: 4, name: "Children's Clothing", href: "/children-clothing", img: childrenClothes, },
  { id: 5, name: "Dresses", href: "/dresses", img: dress },
  { id: 6, name: "Paints for Women", href: "/paints-women", img: paintsWommen },
  { id: 7, name: "Haircuts", href: "/haircuts", img: cut },
  { id: 8, name: "Paints for Men", href: "/paints-men", img: paintsMens },
  { id: 9, name: "Caps", href: "/caps", img: cap },
  { id: 10, name: "Paints for Women 2", href: "/paints-women-2", img: paintsWommen2, },
  { id: 11, name: "Perfume for Men", href: "/perfume-men", img: parfanMens },
  { id: 12, name: "Perfume for Women", href: "/perfume-women", img: parfanWommen, },
  { id: 13, name: "Shoes for Women", href: "/shoes-women", img: shosewommen },
  { id: 14, name: "Shoes for Men", href: "/shoes-men", img: shoseMen },
  { id: 15, name: "Chemese", href: "/chemese", img: chemese },
  { id: 16, name: "T-Shirts for Women", href: "/t-shirts-women", img: T_ShirtWommen, },
];
